/soc/oplus,comm/oplus,reserve_chg_soc 0x1
/soc/oplus,comm/oplus_spec,vbat_charging_uv_thr_mv 0xa8c
/soc/oplus,comm/oplus_spec,vbat_uv_thr_mv 0xaf0
/soc/oplus,comm/oplus,chg_shutdown_max_mv 0xaf0
/soc/oplus,comm/oplus,hidden_soc_percent 0x1
